import {AiFillStar} from "react-icons/ai";
const data = [
    {
        id: '1',
        img:'https://m.media-amazon.com/images/I/71OC2YxyQKL._UX569_.jpg',
        name:'Nike T-Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1259',
        review: '(123 reviews)',
        company:'Nike',
        color:'black',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '2',
        img:'https://m.media-amazon.com/images/I/71upy64aw2L._UY550_.jpg',
        name:'Nike T-Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1267',
        review: '(123 reviews)',
        company:'Nike',
        color:'white',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '3',
        img:'https://m.media-amazon.com/images/I/51mAT-nKvQL._UX425_.jpg',
        name:'Nike T-Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'949',
        review: '(123 reviews)',
        company:'Nike',
        color:'blue',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '4',
        img:'https://m.media-amazon.com/images/I/81bbBSAFtsL._UY550_.jpg',
        name:'Nike Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'1008',
        review: '(123 reviews)',
        company:'Nike',
        color:'grey',
        category: 't-shirt',
        gender: 'women',
    },
    {
        id: '5',
        img:'https://m.media-amazon.com/images/I/71s5RLxerlL._UY550_.jpg',
        name:'Nike dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'639',
        review: '(123 reviews)',
        company:'Nike',
        color:'TRACRE',
        category: 'dress',
        gender: 'women',
    },
    {
        id: '6',
        img:'https://m.media-amazon.com/images/I/61EXMOdfBGL._UX425_.jpg',
        name:'U.S. POLO Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1949',
        review: '(123 reviews)',
        company:'U.S. POLO',
        color:'black',
        category: 'shirt',
        gender: 'men',
    },
    {
        id: '7',
        img:'https://m.media-amazon.com/images/I/61gXGnVz4sL._UX425_.jpg',
        name:'U.S. POLO Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1559',
        review: '(123 reviews)',
        company:'U.S. POLO',
        color:'green',
        category: 'shirt',
        gender: 'men',
    },
    {
        id: '8',
        img:'https://m.media-amazon.com/images/I/61sRgHrid+L._UX425_.jpg',
        name:'U.S. POLO Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1679',
        review: '(123 reviews)',
        company:'U.S. POLO',
        color:'white',
        category: 'shirt',
        gender: 'men',
    },
    {
        id: '9',
        img:'https://m.media-amazon.com/images/I/71LnwZWnVrL._UY550_.jpg',
        name:'U.S. POLO Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1049',
        review: '(123 reviews)',
        company:'U.S. POLO',
        color:'black',
        category: 'shirt',
        gender: 'men',
    },
    {
        id: '10',
        img:'https://m.media-amazon.com/images/I/71VFmKtewkL._UX425_.jpg',
        name:'U.S. POLO Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1619',
        review: '(123 reviews)',
        company:'U.S. POLO',
        color:'white',
        category: 'shirt',
        gender: 'men',
    },
    {
        id: '11',
        img:'https://m.media-amazon.com/images/I/51Ka1d0pfmL._UX425_.jpg',
        name:'U.S. POLO Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'1602',
        review: '(123 reviews)',
        company:'U.S. POLO',
        color:'pink',
        category: 'shirt',
        gender: 'men',
    },
    {
        id: '12',
        img:'https://m.media-amazon.com/images/I/81S-mnPHncL._UY550_.jpg',
        nmae:'U.S. POLO T-Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'869',
        review: '(123 reviews)',
        company:'U.S. POLO',
        color:'green',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '13',
        img:'https://m.media-amazon.com/images/I/616GSwig2DL._UY550_.jpg',
        name:'Dennis Lingo Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'499',
        review: '(123 reviews)',
        company:'Dennis Lingo',
        color:'black',
        category: 'shirt',
        gender: 'men',

    },
    {
        id: '14',
        img:'https://m.media-amazon.com/images/I/61XzMtVz3PL._UY550_.jpg',
        name:'Dennis Lingo Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'486',
        review: '(123 reviews)',
        company:'Dennis Lingo',
        color:'green',
        category: 'shirt',
        gender: 'men',

    },
    {
        id: '15',
        img:'https://m.media-amazon.com/images/I/61DGAlvxRLL._UY550_.jpg',
        name:'Dennis Lingo Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'549',
        review: '(123 reviews)',
        company:'Dennis Lingo',
        color:'blue',
        category: 'shirt',
        gender: 'men',

    },
    {
        id: '16',
        img:'https://m.media-amazon.com/images/I/91PUf68eaCL._UY550_.jpg',
        name:'Allen Solly Polo',
        star:<AiFillStar className="rating-star"/>,
        Price:'524',
        review: '(123 reviews)',
        company:'Allen Solly',
        color:'green',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '17',
        img:'https://m.media-amazon.com/images/I/81eVonPUBgL._UY550_.jpg',
        name:'Allen Solly Polo',
        star:<AiFillStar className="rating-star"/>,
        Price:'734',
        review: '(123 reviews)',
        company:'Allen Solly',
        color:'black',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '18',
        img:'https://m.media-amazon.com/images/I/71Wt2zVTMCL._UY550_.jpg',
        name:'Van Heusen T-Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'493',
        review: '(123 reviews)',
        company:'Van Heusen',
        color:'orange',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '19',
        img:'https://m.media-amazon.com/images/I/61f5Gdl9+bL._UX522_.jpg',
        name:'Van Heusen T-Shirt ',
        star:<AiFillStar className="rating-star"/>,
        Price:'799',
        review: '(123 reviews)',
        company:'Van Heusen',
        color:'blue',
        category: 't-shirt',
        gender: 'men',
    },
    {
        id: '20',
        img:'https://m.media-amazon.com/images/I/81yzKs+QCpL._UY550_.jpg',
        name:'IndianG Co Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'567',
        review: '(123 reviews)',
        company:'The Indian Garage Co',
        color:'white',
        category: 'shirt',
        gender: 'men',
    },
    {
        id: '21',
        img:'https://m.media-amazon.com/images/I/51XiLzLLwRL._UX522_.jpg',
        name:'IndianG Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'476',
        review: '(123 reviews)',
        company:'The Indian Garage Co',
        color:'grey',
        category: 'shirt',
        gender: 'men',
    }, {
        id: '22',
        img:'https://m.media-amazon.com/images/I/61ZbKLlt0sL._UY550_.jpg',
        name:'DennisLingo Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'519',
        review: '(123 reviews)',
        company:'Dennis Lingo',
        color:'black',
        category: 'shirt',
        gender: 'men',
    }, {
        id: '23',
        img:'https://m.media-amazon.com/images/I/71n9ObrgbeL._UY550_.jpg',
        name:'Lyriq Shirt',
        star:<AiFillStar className="rating-star"/>,
        Price:'199',
        review: '(123 reviews)',
        company:'Lyriq',
        color:'green',
        category: 'shirt',
        gender: 'men',
    }, {
        id: '24',
        img:'https://m.media-amazon.com/images/I/51boAn+-zyL._UY550_.jpg',
        name:'PeterEngland Pants',
        star:<AiFillStar className="rating-star"/>,
        Price:'749',
        review: '(123 reviews)',
        company:'Peter England',
        color:'grey',
        category: 'pant',
        gender: 'men',
    }, {
        id: '25',
        img:'https://m.media-amazon.com/images/I/81BwbIT+pQL._UY550_.jpg',
        name:'PepeJeans Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'1005',
        review: '(123 reviews)',
        company:'Pepe',
        color:'blue',
        category: 'pant',
        gender: 'men',
    }, {
        id: '26',
        img:'https://m.media-amazon.com/images/I/81N1y-Ogz0L._UY550_.jpg',
        name:'PepeJeans Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'1679',
        review: '(123 reviews)',
        company:'Pepe',
        color:'black',
        category: 'pant',
        gender: 'men',
    }, {
        id: '27',
        img:'https://m.media-amazon.com/images/I/A1LS4YQ6JkL._UY550_.jpg',
        name:'BUFFALO Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'1499',
        review: '(123 reviews)',
        company:'Buffalo',
        color:'blue',
        category: 'pant',
        gender: 'men',

    }, {
        id: '28',
        img:'https://m.media-amazon.com/images/I/71xuLy+MVvL._UY550_.jpg',
        name:'BUFFALO Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'11691',
        review: '(123 reviews)',
        company:'Buffalo',
        color:'black',
        category: 'pant',
        gender: 'men',
    }, {
        id: '29',
        img:'https://m.media-amazon.com/images/I/519Y1-mWqnL._UY550_.jpg',
        name:'PETERENGLAND JEANS',
        star:<AiFillStar className="rating-star"/>,
        Price:'979',
        review: '(123 reviews)',
        company:'Peter England',
        color:'black',
        category: 'pant',
        gender: 'men',
    }, {
        id: '30',
        img:'https://m.media-amazon.com/images/I/51aX5Cam39L._UX522_.jpg',
        name:'RedTape Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'1139',
        review: '(123 reviews)',
        company:'Red Tape',
        color:'grey',
        category: 'pant',
        gender: 'men',
    }, {
        id: '31',
        img:'https://m.media-amazon.com/images/I/51p2pZ5OC+L._UX522_.jpg',
        name:'RedTape Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'1139',
        review: '(123 reviews)',
        company:'Red Tape',
        color:'brown',
        category: 'pant',
        gender: 'men',
    }, {
        id: '32',
        img:'https://m.media-amazon.com/images/I/811fgMOkPUS._UY550_.jpg',
        name:'RedTape Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'1029',
        review: '(123 reviews)',
        company:'Red Tape',
        color:'blue',
        category: 'pant',
        gender: 'men',
    }, {
        id: '34',
        img:'https://m.media-amazon.com/images/I/41FMXwJQoSL._UX522_.jpg',
        name:'RedTape Jeans',
        star:<AiFillStar className="rating-star"/>,
        Price:'1785',
        review: '(123 reviews)',
        company:'Red Tape',
        color:'black',
        category: 'pant',
        gender: 'men',
    }, {
        id: '35',
        img:'https://m.media-amazon.com/images/I/614GLJ5TL3L._UY550_.jpg',
        name:'Harpa Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'399',
        review: '(123 reviews)',
        company:'Harpa',
        color:'black',
        category: 'dress',
        gender: 'women',
    }, {
        id: '36',
        img:'https://m.media-amazon.com/images/I/61N2jrHsAVS._UX522_.jpg',
        name:'Harpa Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'844',
        review: '(123 reviews)',
        company:'Harpa',
        color:'blue',
        category: 'dress',
        gender: 'women',
    }, {
        id: '37',
        img:'https://m.media-amazon.com/images/I/613DBLEr6ML._UX522_.jpg',
        name:'Harpa Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'719',
        review: '(123 reviews)',
        company:'Harpa',
        color:'violet',
        category: 'dress',
        gender: 'women',
    }, {
        id: '38',
        img:'https://m.media-amazon.com/images/I/81TZq+NojeL._UY550_.jpg',
        name:'Lymio dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'599',
        review: '(123 reviews)',
        company:'Lymio',
        color:'brown',
        category: 'dress',
        gender: 'women',
    }, {
        id: '39',
        img:'https://m.media-amazon.com/images/I/71GxB8DJLyL._UY550_.jpg',
        name:'Shasmi dress ',
        star:<AiFillStar className="rating-star"/>,
        Price:'659',
        review: '(123 reviews)',
        company:'Shasmi',
        color:'blue',
        category: 'dress',
        gender: 'women',
    }, {
        id: '40',
        img:'https://m.media-amazon.com/images/I/61F60dHGhPL._UY550_.jpg',
        name:'GRECIILOOKS dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'499',
        review: '(123 reviews)',
        company:'GRECIILOOKS',
        color:'black',
        category: 'dress',
        gender: 'women',
    }, {
        id: '41',
        img:'https://m.media-amazon.com/images/I/817S2-D18WL._UY550_.jpg',
        name:'Janasya Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'702',
        review: '(123 reviews)',
        company:'Janasya',
        color:'red',
        category: 'dress',
        gender: 'women',
    }, {
        id: '42',
        img:'https://m.media-amazon.com/images/I/81cmFJqe3iL._UY550_.jpg',
        name:'Janasya Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'799',
        review: '(123 reviews)',
        company:'Janasya',
        color:'violet',
        category: 'dress',
        gender: 'women',
    }, {
        id: '43',
        img:'https://m.media-amazon.com/images/I/71GUdMJfo-L._UX522_.jpg',
        name:'DEEBACO Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'1578',
        review: '(123 reviews)',
        company:'DEEBACO',
        color:'red',
        category: 'dress',
        gender: 'women',
    }, {
        id: '44',
        img:'https://m.media-amazon.com/images/I/81CQ9IwxgsL._UY550_.jpg',
        name:'Janasya Dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'799',
        review: '(123 reviews)',
        company:'Janasya',
        color:'yellow',
        category: 'dress',
        gender: 'women',
    }, {
        id: '45',
        img:'https://m.media-amazon.com/images/I/71iDUTHzW2L._SY550._SX._UX._SY._UY_.jpg',
        name:'Lymio Dress ',
        star:<AiFillStar className="rating-star"/>,
        Price:'549',
        review: '(123 reviews)',
        company:'Lymio',
        color:'white',
        category: 'dress',
        gender: 'women',
    }, {
        id: '46',
        img:'https://m.media-amazon.com/images/I/51-txKACV0L._UX522_.jpg',
        name:'DEEBACO dress',
        star:<AiFillStar className="rating-star"/>,
        Price:'911',
        review: '(123 reviews)',
        company:'DEEBACO',
        color:'purple',
        category: 'dress',
        gender: 'women',

    }, {
        id: '47',
        img:'https://m.media-amazon.com/images/I/61XlDZtlgLL._UX522_.jpg',
        name:'Campus Sutra Jacket',
        star:<AiFillStar className="rating-star"/>,
        Price:'999',
        review: '(123 reviews)',
        company:'Campus Sutra',
        color:'green',
        category: 'Jacket',
        gender: 'women',
    }, {
        id: '48',
        img:'https://m.media-amazon.com/images/I/51O0kutuqBL._UX522_.jpg',
        name:'Leather Retail®',
        star:<AiFillStar className="rating-star"/>,
        Price:'1822',
        review: '(123 reviews)',
        company:'Leather Retail',
        color:'brown',
        category: 'Jacket',
        gender: 'women',
    }, {
        id: '49',
        img:'https://m.media-amazon.com/images/I/81iiPvmfJvL._UY550_.jpg',
        name:'FUNDAY Jacket',
        star:<AiFillStar className="rating-star"/>,
        Price:'331',
        review: '(123 reviews)',
        company:'FUNDAY FASHION',
        color:'blue',
        category: 'Jacket',
        gender: 'women',
    }, {
        id: '50',
        img:'https://m.media-amazon.com/images/I/715sw+tHo2L._UX522_.jpg',
        name:'DROBE Jacket',
        star:<AiFillStar className="rating-star"/>,
        Price:'919',
        review: '(123 reviews)',
        company:'DEOBE',
        color:'green',
        category: 'Jacket',
        gender: 'women',
    }, {
        id: '51',
        img:'https://m.media-amazon.com/images/I/41zXt+swb3L._UX385_.jpg',
        name:'BE SAVAGE Jacket',
        star:<AiFillStar className="rating-star"/>,
        Price:'767',
        review: '(123 reviews)',
        company:'BE SAVAGE',
        color:'black',
        category: 'Jacket',
        gender: 'men',
    }, {
        id: '52',
        img:'https://m.media-amazon.com/images/I/51toToq6V2L._UX522_.jpg',
        name:'Koverify Solid ',
        star:<AiFillStar className="rating-star"/>,
        Price:'799',
        review: '(123 reviews)',
        company:'Koverify',
        color:'red',
        category: 'Jacket',
        gender: 'men & women',
    }, {
        id: '53',
        img:'https://m.media-amazon.com/images/I/81KhfZKUtgL._UY550_.jpg',
        name:'Allen Solly Jacket',
        star:<AiFillStar className="rating-star"/>,
        Price:'1539',
        review: '(123 reviews)',
        company:'Allen Solly',
        color:'grey',
        category: 'Jacket',
        gender: 'men',
    },
];
export default data;